export const homepageselector ={
    productfirsttitle:'Espresso ',
    productfistvalue:'$10.00',
    productfirstbox:'[data-cy="Espresso"]',
    productsecondtitle:'Espresso Macchiato ',
    productsecondvalue:'$12.00',
    productsecondbox:'[data-cy="Espresso-Macchiato"]',
    productthirdtitle:'Cappuccino ',
    productthirdvalue:'$19.00',
    productthirdbox:'[data-cy="Cappuccino"]',
    productfourtitle:'Mocha ',
    productfourvalue:'$8.00',
    productfourbox:'[data-cy="Mocha"]',
    productfivetitle:'Flat White ',
    productfivevalue:'$18.00',
    productfivebox:'[data-cy="Flat-White"]',
    productsixtitle:'Americano ',
    productsixvalue:'$7.00',
    productsixbox:'[data-cy="Americano"]',
    productseventitle:'Cafe Latte ',
    productsevenvalue:'$16.00',
    productsevenbox:'[data-cy="Cafe-Latte"]',
    producteighttitle:'Espresso Con Panna ',
    producteightvalue:'$14.00',
    producteightbox:'[data-cy="Espresso-Con Panna"]',
    productninetitle:'Cafe Breve ',
    productninevalue:'$15.00',
    productninebox:'[data-cy="Cafe-Breve"]',
    total:'[aria-label="Proceed to checkout"]',
    Verifyproductbyhover:'li.list-item',
    cart:'[aria-label="Cart page"]',
    extracup:'.promo',
    extracuptitle:'.promo>span',
    yesbtn:'.yes',
    paymentdetailspop:'.modal-content.size',
    paymentdetailspoptitle:'.modal-content.size>section>h1',
    paymentdetailspopparag:'.modal-content > p',
    paymentfrom:'form[aria-label="Payment form"]',
    paymentnamelable:'label[for="name"]',
    paymentnameinput:'input#name',
    paymentsubmitbtn:'button#submit-payment',
    



}